### PR TITLE
Feature/inclusion custom environment

### PR DESCRIPTION
**Pull request by upperxcode**
Congratulations on the excellent work. The zero configuration is really good, but working in development I found it very stuck, so I decided to implement a way to launch this in another way too.

### CODE REVIEW

**Comment by felixblaschke** [comment]
Thank you. I looked at your PR. At the first glance I have a bad feeling about a second parameter, that enforced an untyped configuration, that mimics the environment variables concept.

Can you describe the problem you observed? Was it port collision? Or turning hotreload on/off? If I can understand why you avoid using environment variables, maybe we can find a good solution, together.

**Comment by davidmartos96** [comment]
@felixblaschke How about optional nullable parameters for those 3 options? I agree with @upperxcode that it could be a bit confusing to get the examples running without messing with environment variables. The env logic could be kept, but maybe have optional parameters that could override that.

**Comment by felixblaschke** [comment]
@davidmartos96 The examples should work even if no environment variable is set. It will fallback to default setting. That's why I call it zero configuration. 😄 

So this might not be the real problem (getting examples to run), but I am trying to reveal it :-)

Please understand I am very defense on adding configuration to something called "zero configuration".

If we add optional parameters, which is dominant? The env variables or the coded one?

**Comment by davidmartos96** [comment]
@felixblaschke 
> Please understand I am very defense on adding configuration to something called "zero configuration".

Good point, 😅 although I don't think "optional" parameters with a default value would go against that statement.
Maybe all that it's missing is an example on how to change those values from within the code. 

Regarding the order of preference I would say they do not interfere.
optional param if provided -> En variable if set -> Shelf plus default

**Comment by felixblaschke** [comment]
> Regarding the order of preference I would say they do not interfere.
> optional param if provided -> Env variable if set -> Shelf plus default

So basically we want here a feature to **bake-in a certain port** via code, right?

**Comment by davidmartos96** [comment]
@felixblaschke I can't talk for @upperxcode , but for me I would say yes. I think Dart / Flutter coders, specially beginners, are more likely to know how to change the port via an optional parameter than with environment variables.

**Comment by felixblaschke** [comment]
I wrote everything up as an issue: https://github.com/felixblaschke/shelf_plus/issues/2

I also came up with supporting `.env` files as an additional option.

**Comment by upperxcode** [comment]
> Obrigada. Eu olhei para o seu PR. À primeira vista, tenho um mau pressentimento sobre um segundo parâmetro, que impõe uma configuração sem tipo, que imita o conceito de variáveis ​​de ambiente.
> 
> Você pode descrever o problema que observou? Foi uma colisão no porto? Ou ligando / desligando o hotreload? Se eu puder entender por que você evita usar variáveis ​​de ambiente, talvez possamos encontrar uma boa solução, juntos.

Hi. I do not avoid environment variables, I think that in production it is the best option. I just think it is more productive, when you are testing more than one application to be able to climb on different doors, or when one door seems busy you can test on another and then solve the ok door. The link I made to Map can come from an .env file, I just think that, as is common for the application, could be an independent implementation. I still have some difficulties with null-safety and I may have added too much code.

**Pull request closed without merging**
